import 'package:flutter/material.dart';

/* UndefinedNode buttons
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedButtonsWidget31 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
