import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedContributeWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedWidget15.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget82.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle4Widget12.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedHowtodmininstagramWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle4Widget10.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget86.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle4Widget11.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedEldermanWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedElderlearnWidget25.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedEldermangmailcomWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedFrame8Widget20.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAIchatbotWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedLanguageWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedButtonsWidget26.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle2Widget48.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedSettingsWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget84.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget85.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedContactinfoWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle5Widget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle3Widget70.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget83.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedAnimalcardWidget81.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget2/generated/GeneratedRectangle3Widget69.dart';

/* Frame dashboard animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimateWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget25(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget81(),
              ),
              Positioned(
                left: -26.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget20(),
              ),
              Positioned(
                left: 30.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget82(),
              ),
              Positioned(
                left: 30.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget83(),
              ),
              Positioned(
                left: 30.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget84(),
              ),
              Positioned(
                left: 30.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget85(),
              ),
              Positioned(
                left: 30.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget86(),
              ),
              Positioned(
                left: 30.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 391.0,
                height: 27.0,
                child: GeneratedWidget15(),
              ),
              Positioned(
                left: 8.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedHowtodmininstagramWidget1(),
              ),
              Positioned(
                left: 105.0,
                top: -63.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 925.0,
                child: GeneratedRectangle2Widget48(),
              ),
              Positioned(
                left: 109.0,
                top: 250.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle3Widget69(),
              ),
              Positioned(
                left: 108.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle3Widget70(),
              ),
              Positioned(
                left: 62.0,
                top: 324.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 37.0,
                child: GeneratedContactinfoWidget(),
              ),
              Positioned(
                left: 174.0,
                top: 252.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 41.0,
                child: GeneratedAIchatbotWidget(),
              ),
              Positioned(
                left: 64.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 40.0,
                child: GeneratedEldermanWidget(),
              ),
              Positioned(
                left: 109.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle4Widget10(),
              ),
              Positioned(
                left: 109.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle4Widget11(),
              ),
              Positioned(
                left: 107.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle5Widget4(),
              ),
              Positioned(
                left: 58.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 40.0,
                child: GeneratedLanguageWidget(),
              ),
              Positioned(
                left: 180.0,
                top: 48.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 111.0,
                child: GeneratedRectangle4Widget12(),
              ),
              Positioned(
                left: 63.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 355.0,
                height: 40.0,
                child: GeneratedSettingsWidget(),
              ),
              Positioned(
                left: 100.0,
                top: 187.0,
                right: null,
                bottom: null,
                width: 282.0,
                height: 29.0,
                child: GeneratedEldermangmailcomWidget(),
              ),
              Positioned(
                left: 256.0,
                top: 741.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 50.0,
                child: GeneratedButtonsWidget26(),
              ),
              Positioned(
                left: 65.0,
                top: 451.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 37.0,
                child: GeneratedContributeWidget(),
              )
            ]),
      ),
    ));
  }
}
