import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedAnimalcardWidget89.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedAnimalcardWidget90.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedAnimalcardWidget91.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedRectangle2Widget51.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedWidget20.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedAnimalcardWidget92.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedWidget19.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget3/generated/GeneratedNaviconsWidget4.dart';

/* Frame dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedDashboardanimateWidget1'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 32.0,
                  top: 91.0,
                  right: null,
                  bottom: null,
                  width: 238.0,
                  height: 39.0,
                  child: GeneratedWidget19(),
                ),
                Positioned(
                  left: 30.0,
                  top: 43.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 24.0,
                  child: GeneratedNaviconsWidget4(),
                ),
                Positioned(
                  left: -28.0,
                  top: 225.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 587.0,
                  child: GeneratedRectangle2Widget51(),
                ),
                Positioned(
                  left: 30.0,
                  top: 830.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 106.0,
                  child: GeneratedAnimalcardWidget89(),
                ),
                Positioned(
                  left: 30.0,
                  top: 957.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget90(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1079.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget91(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1201.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 104.0,
                  child: GeneratedAnimalcardWidget92(),
                ),
                Positioned(
                  left: 29.0,
                  top: 132.0,
                  right: null,
                  bottom: null,
                  width: 559.0,
                  height: 27.0,
                  child: GeneratedWidget20(),
                )
              ]),
        ),
      ),
    ));
  }
}
