import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedElderlearnWidget24.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedAnimalcardWidget79.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedScreenshot20220928at2261Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedScreenshot20220928at2231Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedRectangle2Widget45.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedAnimalcardWidget80.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedNaviconsWidget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedAnimalcardWidget77.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedScreenshot20220928at2241Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedPleaseselectryourpreferedlanguageWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate1widget/generated/GeneratedAnimalcardWidget78.dart';

/* Frame dashboard animate1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget24(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedNaviconsWidget3(),
              ),
              Positioned(
                left: -28.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 554.0,
                child: GeneratedRectangle2Widget45(),
              ),
              Positioned(
                left: 30.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget77(),
              ),
              Positioned(
                left: 30.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget78(),
              ),
              Positioned(
                left: 250.0,
                top: 287.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 95.0,
                child: GeneratedScreenshot20220928at2231Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget79(),
              ),
              Positioned(
                left: 30.0,
                top: 655.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget80(),
              ),
              Positioned(
                left: 30.0,
                top: 157.0,
                right: null,
                bottom: null,
                width: 272.0,
                height: 88.0,
                child: GeneratedPleaseselectryourpreferedlanguageWidget(),
              ),
              Positioned(
                left: 253.0,
                top: 530.0,
                right: null,
                bottom: null,
                width: 92.0,
                height: 95.0,
                child: GeneratedScreenshot20220928at2241Widget(),
              ),
              Positioned(
                left: 264.0,
                top: 663.0,
                right: null,
                bottom: null,
                width: 81.0,
                height: 85.0,
                child: GeneratedScreenshot20220928at2261Widget(),
              )
            ]),
      ),
    ));
  }
}
