import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedwidget24/generated/GeneratedWidget26.dart';
import 'package:flutterapp/elderlearnapp/generatedwidget24/generated/GeneratedWidget27.dart';
import 'package:flutterapp/elderlearnapp/generatedwidget24/generated/GeneratedRelearnWidget4.dart';
import 'package:flutterapp/elderlearnapp/generatedwidget24/generated/GeneratedFrame5Widget4.dart';

/* Frame  
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedWidget24 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 559.0,
      height: 27.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 142.0,
              height: 27.0,
              child: GeneratedFrame5Widget4(),
            ),
            Positioned(
              left: 161.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 131.0,
              height: 25.0,
              child: GeneratedWidget26(),
            ),
            Positioned(
              left: 309.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 182.0,
              height: 28.0,
              child: GeneratedWidget27(),
            ),
            Positioned(
              left: 505.0,
              top: 2.0,
              right: null,
              bottom: null,
              width: 59.0,
              height: 28.0,
              child: GeneratedRelearnWidget4(),
            )
          ]),
    ));
  }
}
