import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedgroup1widget4/generated/GeneratedCurrentWidget7.dart';
import 'package:flutterapp/elderlearnapp/generatedgroup1widget4/generated/GeneratedPlayWidget28.dart';
import 'package:flutterapp/elderlearnapp/generatedgroup1widget4/generated/GeneratedRectangle2Widget46.dart';
import 'package:flutterapp/elderlearnapp/generatedgroup1widget4/generated/GeneratedBufferedWidget13.dart';
import 'package:flutterapp/elderlearnapp/generatedgroup1widget4/generated/GeneratedFullScreenWidget19.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup1Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 362.0,
      height: 27.999961853027344,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 2.153846263885498,
              child: GeneratedBufferedWidget13(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 362.0,
              height: 2.153846263885498,
              child: GeneratedCurrentWidget7(),
            ),
            Positioned(
              left: 0.0,
              top: 2.15380859375,
              right: null,
              bottom: null,
              width: 362.0,
              height: 25.846153259277344,
              child: GeneratedRectangle2Widget46(),
            ),
            Positioned(
              left: 348.99072265625,
              top: 9.3333740234375,
              right: null,
              bottom: null,
              width: 4.525000095367432,
              height: 11.48717975616455,
              child: GeneratedFullScreenWidget19(),
            ),
            Positioned(
              left: 8.484375,
              top: 9.3333740234375,
              right: null,
              bottom: null,
              width: 3.53515625,
              height: 11.48717975616455,
              child: GeneratedPlayWidget28(),
            )
          ]),
    ));
  }
}
