import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedButtonsWidget13.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedAnimalcardWidget21.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedNoWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedYesWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedFrame8Widget5.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedElderlearnWidget6.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedHowtoDirectMessagesomeoneinInstagramWidget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget3/generated/GeneratedAnimalcardWidget19.dart';

/* Frame dashboard animate00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate00Widget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget6(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget19(),
              ),
              Positioned(
                left: -35.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 515.0,
                height: 605.0,
                child: GeneratedFrame8Widget5(),
              ),
              Positioned(
                left: -26.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 120.0,
                child: GeneratedHowtoDirectMessagesomeoneinInstagramWidget3(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 266.0,
                child: GeneratedAnimalcardWidget21(),
              ),
              Positioned(
                left: 89.0,
                top: 345.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedYesWidget(),
              ),
              Positioned(
                left: 219.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedNoWidget(),
              ),
              Positioned(
                left: 266.0,
                top: 752.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 50.0,
                child: GeneratedButtonsWidget13(),
              )
            ]),
      ),
    ));
  }
}
