import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedWhatsAppImage20221002at3031Widget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedAnimalcardWidget31.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedFrame8Widget9.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedAnimalcardWidget33.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedHowtoDirectMessagesomeoneinInstagramWidget7.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedElderlearnWidget10.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedRectangle8Widget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedYesWidget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedRectangle5Widget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedNoWidget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedNowclickthesendicontosendyourtextWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget7/generated/GeneratedRectangle7Widget1.dart';

/* Frame dashboard animate00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate00Widget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget10(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget31(),
              ),
              Positioned(
                left: -26.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget9(),
              ),
              Positioned(
                left: -26.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 120.0,
                child: GeneratedHowtoDirectMessagesomeoneinInstagramWidget7(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 266.0,
                child: GeneratedAnimalcardWidget33(),
              ),
              Positioned(
                left: 85.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedYesWidget4(),
              ),
              Positioned(
                left: 219.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedNoWidget4(),
              ),
              Positioned(
                left: 5.0,
                top: -32.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 844.0,
                child: GeneratedWhatsAppImage20221002at3031Widget3(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 74.0,
                child: GeneratedRectangle5Widget2(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 74.0,
                child: GeneratedRectangle6Widget2(),
              ),
              Positioned(
                left: 53.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 70.0,
                child: GeneratedNowclickthesendicontosendyourtextWidget(),
              ),
              Positioned(
                left: 332.0,
                top: 431.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 35.0,
                child: GeneratedRectangle7Widget1(),
              ),
              Positioned(
                left: 336.0,
                top: 436.0,
                right: null,
                bottom: null,
                width: 21.0,
                height: 22.0,
                child: GeneratedRectangle8Widget4(),
              )
            ]),
      ),
    ));
  }
}
