import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget5.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedHowtodmininstagramWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedElderlearnWidget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget/generated/GeneratedAnimalcardWidget3.dart';

/* Frame dashboard animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget(),
              ),
              Positioned(
                left: -26.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 504.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget3(),
              ),
              Positioned(
                left: 30.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget5(),
              ),
              Positioned(
                left: 30.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 391.0,
                height: 27.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 8.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedHowtodmininstagramWidget(),
              )
            ]),
      ),
    ));
  }
}
