import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget7.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedWidget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedFrame8Widget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget9.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget11.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget8.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedWidget12.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget6.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget1/generated/GeneratedAnimalcardWidget10.dart';

/* Frame dashboard animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimateWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 39.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget6(),
              ),
              Positioned(
                left: -26.0,
                top: 196.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget1(),
              ),
              Positioned(
                left: 24.0,
                top: 245.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget7(),
              ),
              Positioned(
                left: 30.0,
                top: 374.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget8(),
              ),
              Positioned(
                left: 26.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget9(),
              ),
              Positioned(
                left: 30.0,
                top: 636.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget10(),
              ),
              Positioned(
                left: 30.0,
                top: 761.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget11(),
              ),
              Positioned(
                left: 47.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedWidget12(),
              )
            ]),
      ),
    ));
  }
}
