import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedAnimalcardWidget66.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedAnimalcardWidget67.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedWidget14.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedNaviconsWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedElderlearnWidget22.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedAnimalcardWidget65.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedAnimalcardWidget69.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedRectangle2Widget40.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedShowingresultsforhowtodmininstagramWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget1/generated/GeneratedAnimalcardWidget68.dart';

/* Frame dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget22(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedNaviconsWidget1(),
              ),
              Positioned(
                left: -28.0,
                top: 225.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedRectangle2Widget40(),
              ),
              Positioned(
                left: 30.0,
                top: 830.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 106.0,
                child: GeneratedAnimalcardWidget65(),
              ),
              Positioned(
                left: 30.0,
                top: 957.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget66(),
              ),
              Positioned(
                left: 30.0,
                top: 1079.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 101.0,
                child: GeneratedAnimalcardWidget67(),
              ),
              Positioned(
                left: 30.0,
                top: 1201.0,
                right: null,
                bottom: null,
                width: 336.0,
                height: 104.0,
                child: GeneratedAnimalcardWidget68(),
              ),
              Positioned(
                left: -16.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 103.0,
                child: GeneratedAnimalcardWidget69(),
              ),
              Positioned(
                left: 57.0,
                top: 158.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedShowingresultsforhowtodmininstagramWidget(),
              ),
              Positioned(
                left: 51.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedWidget14(),
              )
            ]),
      ),
    ));
  }
}
