import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedWhatsAppImage20221002at3031Widget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedYesWidget5.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedAnimalcardWidget34.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedFrame8Widget10.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedHowtoDirectMessagesomeoneinInstagramWidget8.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedElderlearnWidget11.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedRectangle5Widget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedCongratsyouhavesuccessfullytextedonwhatsappWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedAnimalcardWidget36.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedNoWidget5.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget8/generated/GeneratedButtonsWidget14.dart';

/* Frame dashboard animate00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate00Widget8 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget11(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget34(),
              ),
              Positioned(
                left: -26.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget10(),
              ),
              Positioned(
                left: -26.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 120.0,
                child: GeneratedHowtoDirectMessagesomeoneinInstagramWidget8(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 266.0,
                child: GeneratedAnimalcardWidget36(),
              ),
              Positioned(
                left: 85.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedYesWidget5(),
              ),
              Positioned(
                left: 219.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedNoWidget5(),
              ),
              Positioned(
                left: 3.0,
                top: -32.0,
                right: null,
                bottom: null,
                width: 372.0,
                height: 844.0,
                child: GeneratedWhatsAppImage20221002at3031Widget4(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 74.0,
                child: GeneratedRectangle5Widget3(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 119.5,
                child: GeneratedRectangle6Widget3(),
              ),
              Positioned(
                left: 203.0,
                top: 738.0,
                right: null,
                bottom: null,
                width: 139.0,
                height: 56.0,
                child: GeneratedButtonsWidget14(),
              ),
              Positioned(
                left: 58.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 36.0,
                child:
                    GeneratedCongratsyouhavesuccessfullytextedonwhatsappWidget(),
              )
            ]),
      ),
    ));
  }
}
