import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedButtonsWidget3.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedForgetyourpaswordWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedShapeWidget2.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate1widget/generated/GeneratedButtonsWidget2.dart';

/* Frame login animate 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginanimate1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 93.0,
                child: GeneratedWelcomeBackWidget(),
              ),
              Positioned(
                left: 145.0,
                top: -55.0,
                right: null,
                bottom: null,
                width: 350.5934143066406,
                height: 442.0,
                child: GeneratedShapeWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedButtonsWidget2(),
              ),
              Positioned(
                left: 30.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 313.5,
                height: 158.0,
                child: GeneratedFrame3Widget(),
              ),
              Positioned(
                left: 29.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedButtonsWidget3(),
              ),
              Positioned(
                left: 111.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 25.0,
                child: GeneratedForgetyourpaswordWidget(),
              )
            ]),
      ),
    ));
  }
}
