import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedframe9widget/generated/GeneratedFrame9Widget1.dart';

/* Frame Frame 9
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame9Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 506.0,
      height: 587.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: -202.0,
              top: 13.0,
              right: null,
              bottom: null,
              width: 506.0,
              height: 587.0,
              child: GeneratedFrame9Widget1(),
            )
          ]),
    ));
  }
}
