import 'package:flutter/material.dart';
import 'package:flutterapp/helpers/svg/svg.dart';

/* Vector Buffered
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBufferedWidget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Opacity(
      opacity: 0.5,
      child: Container(
        width: 258.0,
        height: 3.0,
        child: SvgWidget(painters: [
          SvgPathPainter.fill()
            ..addPath(
                'M0 1.5C0 0.671573 0.671573 0 1.5 0L256.5 0C257.328 0 258 0.671573 258 1.5C258 2.32843 257.328 3 256.5 3L1.5 3C0.671574 3 0 2.32843 0 1.5Z')
            ..color = Color.fromARGB(255, 95, 95, 95),
        ]),
      ),
    ));
  }
}
