import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialwidget/generated/GeneratedShapeWidget11.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialwidget/generated/GeneratedRectangle2Widget44.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialwidget/generated/GeneratedGroup1Widget3.dart';

/* Frame anmial
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnmialWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedAnmialanimateWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -21.4066162109375,
                  top: -46.0,
                  right: null,
                  bottom: null,
                  width: 453.5933837890625,
                  height: 354.0,
                  child: GeneratedShapeWidget11(),
                ),
                Positioned(
                  left: 28.0,
                  top: 348.0,
                  right: null,
                  bottom: null,
                  width: 319.0,
                  height: 34.0,
                  child: GeneratedGroup1Widget3(),
                ),
                Positioned(
                  left: -40.0,
                  top: 382.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 715.0,
                  child: GeneratedRectangle2Widget44(),
                )
              ]),
        ),
      ),
    ));
  }
}
