import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedNaviconsWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedWidget13.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedAnimalcardWidget61.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedAnimalcardWidget62.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedElderlearnWidget21.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedRectangle2Widget39.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedAnimalcardWidget64.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget/generated/GeneratedAnimalcardWidget63.dart';

/* Frame dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedDashboardanimateWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 32.0,
                  top: 91.0,
                  right: null,
                  bottom: null,
                  width: 156.0,
                  height: 39.0,
                  child: GeneratedElderlearnWidget21(),
                ),
                Positioned(
                  left: 30.0,
                  top: 43.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 24.0,
                  child: GeneratedNaviconsWidget(),
                ),
                Positioned(
                  left: -28.0,
                  top: 225.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 587.0,
                  child: GeneratedRectangle2Widget39(),
                ),
                Positioned(
                  left: 30.0,
                  top: 830.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 106.0,
                  child: GeneratedAnimalcardWidget61(),
                ),
                Positioned(
                  left: 30.0,
                  top: 957.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget62(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1079.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget63(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1201.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 104.0,
                  child: GeneratedAnimalcardWidget64(),
                ),
                Positioned(
                  left: 29.0,
                  top: 132.0,
                  right: null,
                  bottom: null,
                  width: 391.0,
                  height: 27.0,
                  child: GeneratedWidget13(),
                )
              ]),
        ),
      ),
    ));
  }
}
