import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedHowtoDirectMessagesomeoneinInstagramWidget6.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedElderlearnWidget9.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedRectangle5Widget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedYesWidget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedAnimalcardWidget30.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedTypethemessageyouwantedtosendWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedWhatsAppImage20221002at3031Widget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedAnimalcardWidget28.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedFrame8Widget8.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget6/generated/GeneratedNoWidget3.dart';

/* Frame dashboard animate00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate00Widget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget9(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget28(),
              ),
              Positioned(
                left: -26.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget8(),
              ),
              Positioned(
                left: -26.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 120.0,
                child: GeneratedHowtoDirectMessagesomeoneinInstagramWidget6(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 266.0,
                child: GeneratedAnimalcardWidget30(),
              ),
              Positioned(
                left: 85.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedYesWidget3(),
              ),
              Positioned(
                left: 219.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedNoWidget3(),
              ),
              Positioned(
                left: 5.0,
                top: -32.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 844.0,
                child: GeneratedWhatsAppImage20221002at3031Widget2(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 74.0,
                child: GeneratedRectangle5Widget1(),
              ),
              Positioned(
                left: 42.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 74.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 53.0,
                top: 651.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 70.0,
                child: GeneratedTypethemessageyouwantedtosendWidget(),
              )
            ]),
      ),
    ));
  }
}
