import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate02widget2/generated/GeneratedHowtoTextsomeoneinwhatsappWidget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate02widget2/generated/GeneratedAnimalcardWidget57.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate02widget2/generated/GeneratedButtonsWidget23.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate02widget2/generated/GeneratedFrame8Widget19.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate02widget2/generated/GeneratedElderlearnWidget20.dart';

/* Frame dashboard animate02
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate02Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedDashboardanimate03Widget2'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 32.0,
                  top: 91.0,
                  right: null,
                  bottom: null,
                  width: 156.0,
                  height: 39.0,
                  child: GeneratedElderlearnWidget20(),
                ),
                Positioned(
                  left: 30.0,
                  top: 43.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 24.0,
                  child: GeneratedAnimalcardWidget57(),
                ),
                Positioned(
                  left: -26.0,
                  top: 209.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 587.0,
                  child: GeneratedFrame8Widget19(),
                ),
                Positioned(
                  left: -26.0,
                  top: 125.0,
                  right: null,
                  bottom: null,
                  width: 377.0,
                  height: 120.0,
                  child: GeneratedHowtoTextsomeoneinwhatsappWidget2(),
                ),
                Positioned(
                  left: 266.0,
                  top: 752.0,
                  right: null,
                  bottom: null,
                  width: 105.0,
                  height: 50.0,
                  child: GeneratedButtonsWidget23(),
                )
              ]),
        ),
      ),
    ));
  }
}
