import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashanimatewidget/generated/GeneratedShapeWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashanimatewidget/generated/GeneratedButtonsWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashanimatewidget/generated/GeneratedIfyesthisisyourplatformWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashanimatewidget/generated/GeneratedDoyouwanttolearnnewtechnologywithoutothershelpWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashanimatewidget/generated/GeneratedElderlearnWidget.dart';

/* Frame splash animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashanimateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 99.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 213.0,
                height: 57.0,
                child: GeneratedElderlearnWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 470.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 74.0,
                child:
                    GeneratedDoyouwanttolearnnewtechnologywithoutothershelpWidget(),
              ),
              Positioned(
                left: 43.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 50.0,
                child: GeneratedIfyesthisisyourplatformWidget(),
              ),
              Positioned(
                left: 160.0,
                top: -44.0,
                right: null,
                bottom: null,
                width: 342.5934143066406,
                height: 432.0,
                child: GeneratedShapeWidget(),
              ),
              Positioned(
                left: 30.0,
                top: 628.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedButtonsWidget(),
              )
            ]),
      ),
    ));
  }
}
