import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedNoWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedHowtoDirectMessagesomeoneinInstagramWidget4.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedAnimalcardWidget22.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedFrame8Widget6.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedElderlearnWidget7.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedYesWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedAnimalcardWidget24.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedWhatsAppImage20221002at3031Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimate00widget4/generated/GeneratedSelectthepersonorgroupsnametochatWidget.dart';

/* Frame dashboard animate00
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimate00Widget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget7(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget22(),
              ),
              Positioned(
                left: -26.0,
                top: 207.0,
                right: null,
                bottom: null,
                width: 506.0,
                height: 587.0,
                child: GeneratedFrame8Widget6(),
              ),
              Positioned(
                left: -26.0,
                top: 125.0,
                right: null,
                bottom: null,
                width: 377.0,
                height: 120.0,
                child: GeneratedHowtoDirectMessagesomeoneinInstagramWidget4(),
              ),
              Positioned(
                left: 20.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 342.0,
                height: 266.0,
                child: GeneratedAnimalcardWidget24(),
              ),
              Positioned(
                left: 85.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedYesWidget1(),
              ),
              Positioned(
                left: 219.0,
                top: 343.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 31.0,
                child: GeneratedNoWidget1(),
              ),
              Positioned(
                left: 5.0,
                top: -32.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 844.0,
                child: GeneratedWhatsAppImage20221002at3031Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 86.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 48.0,
                top: 613.0,
                right: null,
                bottom: null,
                width: 277.0,
                height: 38.0,
                child: GeneratedSelectthepersonorgroupsnametochatWidget(),
              )
            ]),
      ),
    ));
  }
}
