import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedWidget16.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedHowtodmininstagramWidget2.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedRectangle2Widget49.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedMrbotWidget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedAnimalcardWidget87.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedRectangle3Widget72.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedButtonsWidget27.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedButtonsWidget28.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedRectangle3Widget71.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget3/generated/GeneratedElderlearnWidget26.dart';

/* Frame dashboard animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimateWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget26(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget87(),
              ),
              Positioned(
                left: 8.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedHowtodmininstagramWidget2(),
              ),
              Positioned(
                left: -2.0,
                top: -43.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 168.0,
                child: GeneratedRectangle2Widget49(),
              ),
              Positioned(
                left: -17.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 37.0,
                child: GeneratedMrbotWidget(),
              ),
              Positioned(
                left: 262.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 50.0,
                child: GeneratedButtonsWidget27(),
              ),
              Positioned(
                left: 60.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 169.0,
                child: GeneratedButtonsWidget28(),
              ),
              Positioned(
                left: 25.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 65.0,
                child: GeneratedRectangle3Widget71(),
              ),
              Positioned(
                left: -5.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 392.0,
                height: 201.0,
                child: GeneratedRectangle3Widget72(),
              ),
              Positioned(
                left: 306.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 67.0,
                child: GeneratedImage2Widget(),
              ),
              Positioned(
                left: 67.0,
                top: 587.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 227.0,
                child: GeneratedWidget16(),
              )
            ]),
      ),
    ));
  }
}
