import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedButtonsWidget5.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedForgetyourpaswordWidget1.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedWelcomeBackWidget1.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedButtonsWidget4.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedFrame3Widget1.dart';
import 'package:flutterapp/elderlearnapp/generatedloginanimate2widget/generated/GeneratedShapeWidget3.dart';

/* Frame login animate 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginanimate2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 30.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 178.0,
                height: 93.0,
                child: GeneratedWelcomeBackWidget1(),
              ),
              Positioned(
                left: 30.0,
                top: 618.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedButtonsWidget4(),
              ),
              Positioned(
                left: 30.0,
                top: 415.0,
                right: null,
                bottom: null,
                width: 313.5,
                height: 158.0,
                child: GeneratedFrame3Widget1(),
              ),
              Positioned(
                left: 29.0,
                top: 680.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 47.0,
                child: GeneratedButtonsWidget5(),
              ),
              Positioned(
                left: 111.0,
                top: 764.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 25.0,
                child: GeneratedForgetyourpaswordWidget1(),
              ),
              Positioned(
                left: 145.0,
                top: -60.0,
                right: null,
                bottom: null,
                width: 489.5934143066406,
                height: 573.5,
                child: GeneratedShapeWidget3(),
              )
            ]),
      ),
    ));
  }
}
