import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedButtonsWidget9.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedShapeWidget8.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedButtonsWidget8.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedShapeWidget7.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedWelcomeBackWidget3.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedFrame3Widget3.dart';
import 'package:flutterapp/elderlearnapp/generatedloginwidget/generated/GeneratedForgetyourpaswordWidget3.dart';

/* Frame login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedLoginanimate1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 30.0,
                  top: 299.0,
                  right: null,
                  bottom: null,
                  width: 177.0,
                  height: 93.0,
                  child: GeneratedWelcomeBackWidget3(),
                ),
                Positioned(
                  left: 397.0,
                  top: -54.0,
                  right: null,
                  bottom: null,
                  width: 342.5934143066406,
                  height: 432.0,
                  child: GeneratedShapeWidget7(),
                ),
                Positioned(
                  left: 30.0,
                  top: 618.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 47.0,
                  child: GeneratedButtonsWidget8(),
                ),
                Positioned(
                  left: 30.0,
                  top: 415.0,
                  right: null,
                  bottom: null,
                  width: 313.5,
                  height: 158.0,
                  child: GeneratedFrame3Widget3(),
                ),
                Positioned(
                  left: 29.0,
                  top: 680.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 47.0,
                  child: GeneratedButtonsWidget9(),
                ),
                Positioned(
                  left: 111.0,
                  top: 764.0,
                  right: null,
                  bottom: null,
                  width: 154.0,
                  height: 25.0,
                  child: GeneratedForgetyourpaswordWidget3(),
                ),
                Positioned(
                  left: 152.0,
                  top: -55.0,
                  right: null,
                  bottom: null,
                  width: 489.5934143066406,
                  height: 573.5,
                  child: GeneratedShapeWidget8(),
                )
              ]),
        ),
      ),
    ));
  }
}
