import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedScreenshot20220928at4251Widget.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedImage1Widget5.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedShapeWidget10.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedGroup1Widget2.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedAnimalcardWidget76.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedAnimalcardWidget75.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedButtonsWidget24.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedAnimalcardWidget74.dart';
import 'package:flutterapp/elderlearnapp/generatedanmialanimatewidget/generated/GeneratedRectangle2Widget43.dart';

/* Frame anmial animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAnmialanimateWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 352.0,
                top: -46.0,
                right: null,
                bottom: null,
                width: 441.0,
                height: 342.5,
                child: GeneratedShapeWidget10(),
              ),
              Positioned(
                left: 28.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 319.0,
                height: 34.0,
                child: GeneratedGroup1Widget2(),
              ),
              Positioned(
                left: -12.0,
                top: 382.0,
                right: null,
                bottom: null,
                width: 401.0,
                height: 451.0,
                child: GeneratedRectangle2Widget43(),
              ),
              Positioned(
                left: 13.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 103.0,
                child: GeneratedAnimalcardWidget74(),
              ),
              Positioned(
                left: -12.0,
                top: 633.0,
                right: null,
                bottom: null,
                width: 353.0,
                height: 103.0,
                child: GeneratedAnimalcardWidget75(),
              ),
              Positioned(
                left: 254.0,
                top: 736.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 50.0,
                child: GeneratedButtonsWidget24(),
              ),
              Positioned(
                left: -26.0,
                top: 397.0,
                right: null,
                bottom: null,
                width: 373.0,
                height: 103.0,
                child: GeneratedAnimalcardWidget76(),
              ),
              Positioned(
                left: 352.0,
                top: 403.0,
                right: null,
                bottom: null,
                width: 14.0,
                height: 311.0,
                child: GeneratedScreenshot20220928at4251Widget(),
              ),
              Positioned(
                left: 270.0,
                top: 416.0,
                right: null,
                bottom: null,
                width: 52.0,
                height: 53.0,
                child: GeneratedImage1Widget5(),
              )
            ]),
      ),
    ));
  }
}
