import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedButtonsWidget29.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedRectangle4Widget13.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedElderlearnWidget27.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedMrbotWidget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedRectangle3Widget73.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedRectangle3Widget75.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedImage2Widget1.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedHowtodmininstagramWidget3.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedAnimalcardWidget88.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedWidget18.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedRectangle3Widget74.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedRectangle2Widget50.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedButtonsWidget30.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardanimatewidget4/generated/GeneratedWidget17.dart';

/* Frame dashboard animate
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardanimateWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.circular(30.0),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(30.0),
        ),
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.circular(30.0),
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 32.0,
                top: 91.0,
                right: null,
                bottom: null,
                width: 156.0,
                height: 39.0,
                child: GeneratedElderlearnWidget27(),
              ),
              Positioned(
                left: 30.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 315.0,
                height: 24.0,
                child: GeneratedAnimalcardWidget88(),
              ),
              Positioned(
                left: 8.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 264.0,
                height: 69.0,
                child: GeneratedHowtodmininstagramWidget3(),
              ),
              Positioned(
                left: -2.0,
                top: -43.0,
                right: null,
                bottom: null,
                width: 385.0,
                height: 168.0,
                child: GeneratedRectangle2Widget50(),
              ),
              Positioned(
                left: 108.0,
                top: 315.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 55.0,
                child: GeneratedRectangle3Widget73(),
              ),
              Positioned(
                left: -17.0,
                top: 56.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 37.0,
                child: GeneratedMrbotWidget1(),
              ),
              Positioned(
                left: 262.0,
                top: 100.0,
                right: null,
                bottom: null,
                width: 105.0,
                height: 50.0,
                child: GeneratedButtonsWidget29(),
              ),
              Positioned(
                left: 25.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 65.0,
                child: GeneratedRectangle3Widget74(),
              ),
              Positioned(
                left: -5.0,
                top: 751.0,
                right: null,
                bottom: null,
                width: 392.0,
                height: 201.0,
                child: GeneratedRectangle3Widget75(),
              ),
              Positioned(
                left: 306.0,
                top: 745.0,
                right: null,
                bottom: null,
                width: 71.0,
                height: 67.0,
                child: GeneratedImage2Widget1(),
              ),
              Positioned(
                left: 8.0,
                top: 654.0,
                right: null,
                bottom: null,
                width: 280.0,
                height: 91.0,
                child: GeneratedRectangle4Widget13(),
              ),
              Positioned(
                left: 60.0,
                top: 479.0,
                right: null,
                bottom: null,
                width: 307.0,
                height: 169.0,
                child: GeneratedButtonsWidget30(),
              ),
              Positioned(
                left: 67.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 379.0,
                height: 227.0,
                child: GeneratedWidget17(),
              ),
              Positioned(
                left: 17.0,
                top: 668.0,
                right: null,
                bottom: null,
                width: 263.0,
                height: 166.0,
                child: GeneratedWidget18(),
              )
            ]),
      ),
    ));
  }
}
