import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashwidget/generated/GeneratedShapeWidget1.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashwidget/generated/GeneratedButtonsWidget1.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashwidget/generated/GeneratedWhatdoyouknowabouttheanimalKingdomWidget.dart';
import 'package:flutterapp/elderlearnapp/generatedsplashwidget/generated/GeneratedElderlearnWidget1.dart';

/* Frame splash
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedSplashanimateWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 95.0,
                  top: 406.0,
                  right: null,
                  bottom: null,
                  width: 199.0,
                  height: 49.0,
                  child: GeneratedElderlearnWidget1(),
                ),
                Positioned(
                  left: 43.0,
                  top: 455.0,
                  right: null,
                  bottom: null,
                  width: 290.0,
                  height: 60.0,
                  child: GeneratedWhatdoyouknowabouttheanimalKingdomWidget(),
                ),
                Positioned(
                  left: 396.0,
                  top: -54.0,
                  right: null,
                  bottom: null,
                  width: 342.5934143066406,
                  height: 432.0,
                  child: GeneratedShapeWidget1(),
                ),
                Positioned(
                  left: 30.0,
                  top: 628.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 47.0,
                  child: GeneratedButtonsWidget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
