import 'package:flutter/material.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedAnimalcardWidget71.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedAnimalcardWidget72.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedAnimalcardWidget70.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedRectangle2Widget42.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedAnimalcardWidget73.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedElderlearnWidget23.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedRectangle2Widget41.dart';
import 'package:flutterapp/elderlearnapp/generateddashboardwidget2/generated/GeneratedNaviconsWidget2.dart';

/* Frame dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDashboardWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () =>
          Navigator.pushNamed(context, '/GeneratedDashboardanimate1Widget'),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(30.0),
        child: Container(
          width: 375.0,
          height: 812.0,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(30.0),
          ),
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.circular(30.0),
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 33.0,
                  top: 96.0,
                  right: null,
                  bottom: null,
                  width: 156.0,
                  height: 39.0,
                  child: GeneratedElderlearnWidget23(),
                ),
                Positioned(
                  left: 30.0,
                  top: 43.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 24.0,
                  child: GeneratedNaviconsWidget2(),
                ),
                Positioned(
                  left: -28.0,
                  top: 225.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 587.0,
                  child: GeneratedRectangle2Widget41(),
                ),
                Positioned(
                  left: 30.0,
                  top: 830.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 106.0,
                  child: GeneratedAnimalcardWidget70(),
                ),
                Positioned(
                  left: 30.0,
                  top: 957.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget71(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1079.0,
                  right: null,
                  bottom: null,
                  width: 315.0,
                  height: 101.0,
                  child: GeneratedAnimalcardWidget72(),
                ),
                Positioned(
                  left: 30.0,
                  top: 1201.0,
                  right: null,
                  bottom: null,
                  width: 336.0,
                  height: 104.0,
                  child: GeneratedAnimalcardWidget73(),
                ),
                Positioned(
                  left: -89.0,
                  top: 256.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 555.0,
                  child: GeneratedRectangle2Widget42(),
                )
              ]),
        ),
      ),
    ));
  }
}
